.travis.yml, Makefile.am, builds/check_zproject/ci_build.sh, ci_build.sh, configure.ac, include/fty_common_db_library.h, packaging/debian/control, packaging/debian/fty-common-db.dsc.obs, packaging/redhat/fty-common-db.spec, src/libfty_common_db.pc.in
Solution: Regen; make sure ci_build downloads thinds in correct order.
=> Problem: Travis cannot deal with existing ordering of dependencies.

include/fty_common_db_asset.h, src/fty_common_db_asset.cc
=> Problem: library contains duplicate fun

include/fty_common_db_asset.h, src/fty_common_db_asset.cc
=> Problem: moving function from fty-rest to shared library

include/fty_common_db.h
Solution: Add it.
Signed-off-by: Jana Rapava <JanaRapava@eaton.com>
=> Problem: Fty-asset needs another error type.

include/fty_common_db_asset.h, src/fty_common_db_asset.cc
Solution: fun added: select_asset_elements_by_type, select_links_by_container, list_devices_with_status
Signed-off-by: Barbora Stepankova <BarboraStepankova@eaton.com>
=> Problem: add DB function from metric-tpower

include/fty_common_db_asset.h
=> Problem: Limitations struct shouldn't be here.

include/fty_common_db_asset_insert.h, include/fty_common_db_defs.h, src/fty_common_db_asset_insert.cc
=> Problem: We want to move insert DB code to fty-common-db.

include/fty_common_db_asset_update.h, src/fty_common_db_asset_update.cc
=> Problem: We need to move update DB functions to fty-common-db.

src/fty_common_db_asset.cc
Solution: variable assignment corrected
Signed-off-by: Barbora Stepankova <BarboraStepankova@eaton.com>
=> Problem: tntdb crashes on type error exception

src/fty_common_db_asset_insert.cc
=> Translation enablement for /asset/import.

src/fty_common_db_asset.cc
Solution: Mark them for translation.
=> Problem: Some error messages are propagates to UI via REST API.

src/fty_common_db_asset.cc
Solution: fix log device and fix proper output
=> Problem: logs contains false messages

README.md
=> (S/XS) Add README.

.travis.yml, ci_deploy_obs.sh, configure.ac, packaging/debian/control, packaging/debian/fty-common-db.dsc.obs, packaging/redhat/fty-common-db.spec, project.xml, src/Makemodule.am, src/fty_common_db_classes.h, src/libfty_common_db.pc.in
Signed-off-by: Clement Perrette <clementperrette@eaton.com>
=> Regenerated zproject

include/fty_common_db_limitations.h, src/fty_common_db_limitations.cc
=> Chamge return types to make functions more general.

src/fty_common_db_asset.cc
=> Select v_id_parent_type column in v_web_element table

src/fty_common_db_exception.cc
=> Fixed clang build

src/fty_common_db_asset_insert.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
=> Generate random integer in asset name

src/fty_common_db_asset_insert.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
=> Prevent random ID collision on asset name creation

include/fty_common_db_asset.h, src/fty_common_db_asset.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
=> Add list_devices_with_status (wrapper)

include/fty_common_db_asset.h, src/fty_common_db_asset.cc
Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>
=> Add db helpers for licensing credits
